"""add expires_at to aliases

Revision ID: 0e56b48750ad
Revises: 86e688eef6e8
Create Date: 2026-05-10 14:04:04.836128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e56b48750ad'
down_revision: Union[str, Sequence[str], None] = '86e688eef6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliases', 'expires_at')
    # ### end Alembic commands ###
