"""add created_for to aliases

Revision ID: 12ae1c2c1866
Revises: 5d465f62f4d9
Create Date: 2026-06-13 21:47:37.608087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ae1c2c1866'
down_revision: Union[str, Sequence[str], None] = '5d465f62f4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('created_for', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliases', 'created_for')
    # ### end Alembic commands ###
