"""add pro_until to users

Revision ID: 1d73289a41e6
Revises: 0e56b48750ad
Create Date: 2026-05-12 19:46:43.461423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d73289a41e6'
down_revision: Union[str, Sequence[str], None] = '0e56b48750ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_until')
    # ### end Alembic commands ###
