"""cascade delete emails on alias delete

Revision ID: 2aa858edd7b2
Revises: ff43d6a259bd
Create Date: 2026-05-01 22:02:52.968375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa858edd7b2'
down_revision: Union[str, Sequence[str], None] = 'ff43d6a259bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emails_alias_id_fkey'), 'emails', type_='foreignkey')
    op.create_foreign_key(None, 'emails', 'aliases', ['alias_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.create_foreign_key(op.f('emails_alias_id_fkey'), 'emails', 'aliases', ['alias_id'], ['id'])
    # ### end Alembic commands ###
