"""add label to aliases

Revision ID: 8664820b01e2
Revises: 1d73289a41e6
Create Date: 2026-05-13 20:01:08.339896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8664820b01e2'
down_revision: Union[str, Sequence[str], None] = '1d73289a41e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliases', 'label')
    # ### end Alembic commands ###
