"""add is_custom to aliases

Revision ID: 86e688eef6e8
Revises: a3a58948acb5
Create Date: 2026-05-02 20:27:30.353066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e688eef6e8'
down_revision: Union[str, Sequence[str], None] = 'a3a58948acb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliases', 'is_custom')
    # ### end Alembic commands ###
