"""add leak_detected to aliases

Revision ID: d2d937c4bdfc
Revises: 12ae1c2c1866
Create Date: 2026-06-16 17:01:16.182285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d937c4bdfc'
down_revision: Union[str, Sequence[str], None] = '12ae1c2c1866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aliases', sa.Column('leak_detected', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliases', 'leak_detected')
    # ### end Alembic commands ###
